package v1

import (
	"github.com/gorilla/mux"
	_ "github.com/happilymarrieddad/order-management-v3/api/docs" // docs is generated by Swag CLI
	"github.com/happilymarrieddad/order-management-v3/api/internal/api/v1/addresses"
	"github.com/happilymarrieddad/order-management-v3/api/internal/api/v1/companies"
	"github.com/happilymarrieddad/order-management-v3/api/internal/api/v1/users"
	httpSwagger "github.com/swaggo/http-swagger"
)

// AddRoutes configures the v1 API routes on the given subrouter.
func AddRoutes(r *mux.Router) {
	// Add swagger route. Access it at http://localhost:8080/api/v1/swagger/index.html
	// The empty import of the docs package is necessary for swag to work.
	r.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	// Create a subrouter for the /users resource.
	// This groups all user-related endpoints under /api/v1/users.
	usersRouter := r.PathPrefix("/users").Subrouter()

	// Define the routes for the users resource in a standard RESTful fashion.
	usersRouter.HandleFunc("", users.Create).Methods("POST")
	usersRouter.HandleFunc("/find", users.Find).Methods("POST") // A dedicated find endpoint for complex queries.
	usersRouter.HandleFunc("/{id:[0-9]+}", users.Get).Methods("GET")
	usersRouter.HandleFunc("/{id:[0-9]+}", users.Update).Methods("PUT")
	usersRouter.HandleFunc("/{id:[0-9]+}", users.Delete).Methods("DELETE")

	// Create a subrouter for the /companies resource.
	companiesRouter := r.PathPrefix("/companies").Subrouter()
	companiesRouter.HandleFunc("", companies.Create).Methods("POST")
	companiesRouter.HandleFunc("/find", companies.Find).Methods("POST")
	companiesRouter.HandleFunc("/{id:[0-9]+}", companies.Get).Methods("GET")
	companiesRouter.HandleFunc("/{id:[0-9]+}", companies.Update).Methods("PUT")
	companiesRouter.HandleFunc("/{id:[0-9]+}", companies.Delete).Methods("DELETE")

	// Create a subrouter for the /addresses resource.
	addressesRouter := r.PathPrefix("/addresses").Subrouter()
	addressesRouter.HandleFunc("", addresses.Create).Methods("POST")
	addressesRouter.HandleFunc("/find", addresses.Find).Methods("POST")
	addressesRouter.HandleFunc("/{id:[0-9]+}", addresses.Get).Methods("GET")
	addressesRouter.HandleFunc("/{id:[0-9]+}", addresses.Update).Methods("PUT")
	addressesRouter.HandleFunc("/{id:[0-9]+}", addresses.Delete).Methods("DELETE")
}
