// Code generated by MockGen. DO NOT EDIT.
// Source: ./commodities.go
//
// Generated by this command:
//
//	mockgen -source=./commodities.go -destination=./mocks/commodities.go -package=mock_repos
//

// Package mock_repos is a generated GoMock package.
package mock_repos

import (
	context "context"
	reflect "reflect"

	repos "github.com/happilymarrieddad/order-management-v3/api/internal/repos"
	types "github.com/happilymarrieddad/order-management-v3/api/types"
	gomock "go.uber.org/mock/gomock"
	xorm "xorm.io/xorm"
)

// MockCommoditiesRepo is a mock of CommoditiesRepo interface.
type MockCommoditiesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCommoditiesRepoMockRecorder
	isgomock struct{}
}

// MockCommoditiesRepoMockRecorder is the mock recorder for MockCommoditiesRepo.
type MockCommoditiesRepoMockRecorder struct {
	mock *MockCommoditiesRepo
}

// NewMockCommoditiesRepo creates a new mock instance.
func NewMockCommoditiesRepo(ctrl *gomock.Controller) *MockCommoditiesRepo {
	mock := &MockCommoditiesRepo{ctrl: ctrl}
	mock.recorder = &MockCommoditiesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommoditiesRepo) EXPECT() *MockCommoditiesRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCommoditiesRepo) Create(ctx context.Context, commodity *types.Commodity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, commodity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCommoditiesRepoMockRecorder) Create(ctx, commodity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommoditiesRepo)(nil).Create), ctx, commodity)
}

// CreateTx mocks base method.
func (m *MockCommoditiesRepo) CreateTx(ctx context.Context, tx *xorm.Session, commodity *types.Commodity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTx", ctx, tx, commodity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTx indicates an expected call of CreateTx.
func (mr *MockCommoditiesRepoMockRecorder) CreateTx(ctx, tx, commodity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTx", reflect.TypeOf((*MockCommoditiesRepo)(nil).CreateTx), ctx, tx, commodity)
}

// Find mocks base method.
func (m *MockCommoditiesRepo) Find(ctx context.Context, opts *repos.FindCommoditiesOpts) ([]*types.Commodity, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, opts)
	ret0, _ := ret[0].([]*types.Commodity)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find indicates an expected call of Find.
func (mr *MockCommoditiesRepoMockRecorder) Find(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCommoditiesRepo)(nil).Find), ctx, opts)
}

// Get mocks base method.
func (m *MockCommoditiesRepo) Get(ctx context.Context, id int64) (*types.Commodity, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*types.Commodity)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockCommoditiesRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCommoditiesRepo)(nil).Get), ctx, id)
}

// Update mocks base method.
func (m *MockCommoditiesRepo) Update(ctx context.Context, commodity *types.Commodity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, commodity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCommoditiesRepoMockRecorder) Update(ctx, commodity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCommoditiesRepo)(nil).Update), ctx, commodity)
}

// UpdateTx mocks base method.
func (m *MockCommoditiesRepo) UpdateTx(ctx context.Context, tx *xorm.Session, commodity *types.Commodity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTx", ctx, tx, commodity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTx indicates an expected call of UpdateTx.
func (mr *MockCommoditiesRepoMockRecorder) UpdateTx(ctx, tx, commodity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTx", reflect.TypeOf((*MockCommoditiesRepo)(nil).UpdateTx), ctx, tx, commodity)
}
