// Code generated by MockGen. DO NOT EDIT.
// Source: ./company_attributes.go
//
// Generated by this command:
//
//	mockgen -source=./company_attributes.go -destination=./mocks/company_attributes.go -package=mock_repos CompanyAttributesRepo
//

// Package mock_repos is a generated GoMock package.
package mock_repos

import (
	context "context"
	reflect "reflect"

	repos "github.com/happilymarrieddad/order-management-v3/api/internal/repos"
	types "github.com/happilymarrieddad/order-management-v3/api/types"
	gomock "go.uber.org/mock/gomock"
	xorm "xorm.io/xorm"
)

// MockCompanyAttributesRepo is a mock of CompanyAttributesRepo interface.
type MockCompanyAttributesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyAttributesRepoMockRecorder
	isgomock struct{}
}

// MockCompanyAttributesRepoMockRecorder is the mock recorder for MockCompanyAttributesRepo.
type MockCompanyAttributesRepoMockRecorder struct {
	mock *MockCompanyAttributesRepo
}

// NewMockCompanyAttributesRepo creates a new mock instance.
func NewMockCompanyAttributesRepo(ctrl *gomock.Controller) *MockCompanyAttributesRepo {
	mock := &MockCompanyAttributesRepo{ctrl: ctrl}
	mock.recorder = &MockCompanyAttributesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyAttributesRepo) EXPECT() *MockCompanyAttributesRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCompanyAttributesRepo) Create(ctx context.Context, attr *types.CompanyAttribute) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, attr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCompanyAttributesRepoMockRecorder) Create(ctx, attr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCompanyAttributesRepo)(nil).Create), ctx, attr)
}

// CreateTx mocks base method.
func (m *MockCompanyAttributesRepo) CreateTx(ctx context.Context, tx *xorm.Session, attr *types.CompanyAttribute) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTx", ctx, tx, attr)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTx indicates an expected call of CreateTx.
func (mr *MockCompanyAttributesRepoMockRecorder) CreateTx(ctx, tx, attr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTx", reflect.TypeOf((*MockCompanyAttributesRepo)(nil).CreateTx), ctx, tx, attr)
}

// Delete mocks base method.
func (m *MockCompanyAttributesRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCompanyAttributesRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCompanyAttributesRepo)(nil).Delete), ctx, id)
}

// DeleteTx mocks base method.
func (m *MockCompanyAttributesRepo) DeleteTx(ctx context.Context, tx *xorm.Session, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTx", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTx indicates an expected call of DeleteTx.
func (mr *MockCompanyAttributesRepoMockRecorder) DeleteTx(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTx", reflect.TypeOf((*MockCompanyAttributesRepo)(nil).DeleteTx), ctx, tx, id)
}

// Find mocks base method.
func (m *MockCompanyAttributesRepo) Find(ctx context.Context, opts *repos.FindCompanyAttributesOpts) ([]*types.CompanyAttribute, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, opts)
	ret0, _ := ret[0].([]*types.CompanyAttribute)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find indicates an expected call of Find.
func (mr *MockCompanyAttributesRepoMockRecorder) Find(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCompanyAttributesRepo)(nil).Find), ctx, opts)
}
