// Code generated by MockGen. DO NOT EDIT.
// Source: ./company_attribute_settings.go
//
// Generated by this command:
//
//	mockgen -source=./company_attribute_settings.go -destination=./mocks/company_attribute_settings.go -package=mock_repos CompanyAttributeSettingsRepo
//

// Package mock_repos is a generated GoMock package.
package mock_repos

import (
	context "context"
	reflect "reflect"

	repos "github.com/happilymarrieddad/order-management-v3/api/internal/repos"
	types "github.com/happilymarrieddad/order-management-v3/api/types"
	gomock "go.uber.org/mock/gomock"
	xorm "xorm.io/xorm"
)

// MockCompanyAttributeSettingsRepo is a mock of CompanyAttributeSettingsRepo interface.
type MockCompanyAttributeSettingsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyAttributeSettingsRepoMockRecorder
	isgomock struct{}
}

// MockCompanyAttributeSettingsRepoMockRecorder is the mock recorder for MockCompanyAttributeSettingsRepo.
type MockCompanyAttributeSettingsRepoMockRecorder struct {
	mock *MockCompanyAttributeSettingsRepo
}

// NewMockCompanyAttributeSettingsRepo creates a new mock instance.
func NewMockCompanyAttributeSettingsRepo(ctrl *gomock.Controller) *MockCompanyAttributeSettingsRepo {
	mock := &MockCompanyAttributeSettingsRepo{ctrl: ctrl}
	mock.recorder = &MockCompanyAttributeSettingsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyAttributeSettingsRepo) EXPECT() *MockCompanyAttributeSettingsRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCompanyAttributeSettingsRepo) Create(ctx context.Context, setting *types.CompanyAttributeSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCompanyAttributeSettingsRepoMockRecorder) Create(ctx, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCompanyAttributeSettingsRepo)(nil).Create), ctx, setting)
}

// CreateTx mocks base method.
func (m *MockCompanyAttributeSettingsRepo) CreateTx(ctx context.Context, tx *xorm.Session, setting *types.CompanyAttributeSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTx", ctx, tx, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTx indicates an expected call of CreateTx.
func (mr *MockCompanyAttributeSettingsRepoMockRecorder) CreateTx(ctx, tx, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTx", reflect.TypeOf((*MockCompanyAttributeSettingsRepo)(nil).CreateTx), ctx, tx, setting)
}

// Delete mocks base method.
func (m *MockCompanyAttributeSettingsRepo) Delete(ctx context.Context, ids ...int64) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCompanyAttributeSettingsRepoMockRecorder) Delete(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCompanyAttributeSettingsRepo)(nil).Delete), varargs...)
}

// DeleteTx mocks base method.
func (m *MockCompanyAttributeSettingsRepo) DeleteTx(ctx context.Context, tx *xorm.Session, ids ...int64) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteTx", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTx indicates an expected call of DeleteTx.
func (mr *MockCompanyAttributeSettingsRepoMockRecorder) DeleteTx(ctx, tx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTx", reflect.TypeOf((*MockCompanyAttributeSettingsRepo)(nil).DeleteTx), varargs...)
}

// Find mocks base method.
func (m *MockCompanyAttributeSettingsRepo) Find(ctx context.Context, opts *repos.CompanyAttributeSettingFindOpts) ([]*types.CompanyAttributeSetting, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, opts)
	ret0, _ := ret[0].([]*types.CompanyAttributeSetting)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find indicates an expected call of Find.
func (mr *MockCompanyAttributeSettingsRepoMockRecorder) Find(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCompanyAttributeSettingsRepo)(nil).Find), ctx, opts)
}

// Get mocks base method.
func (m *MockCompanyAttributeSettingsRepo) Get(ctx context.Context, id int64) (*types.CompanyAttributeSetting, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*types.CompanyAttributeSetting)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockCompanyAttributeSettingsRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCompanyAttributeSettingsRepo)(nil).Get), ctx, id)
}

// Update mocks base method.
func (m *MockCompanyAttributeSettingsRepo) Update(ctx context.Context, setting *types.CompanyAttributeSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCompanyAttributeSettingsRepoMockRecorder) Update(ctx, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCompanyAttributeSettingsRepo)(nil).Update), ctx, setting)
}

// UpdateTx mocks base method.
func (m *MockCompanyAttributeSettingsRepo) UpdateTx(ctx context.Context, tx *xorm.Session, setting *types.CompanyAttributeSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTx", ctx, tx, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTx indicates an expected call of UpdateTx.
func (mr *MockCompanyAttributeSettingsRepoMockRecorder) UpdateTx(ctx, tx, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTx", reflect.TypeOf((*MockCompanyAttributeSettingsRepo)(nil).UpdateTx), ctx, tx, setting)
}
