// Code generated by MockGen. DO NOT EDIT.
// Source: ./products.go
//
// Generated by this command:
//
//	mockgen -source=./products.go -destination=./mocks/products.go -package=mock_repos ProductsRepo
//

// Package mock_repos is a generated GoMock package.
package mock_repos

import (
	context "context"
	reflect "reflect"

	repos "github.com/happilymarrieddad/order-management-v3/api/internal/repos"
	types "github.com/happilymarrieddad/order-management-v3/api/types"
	gomock "go.uber.org/mock/gomock"
	xorm "xorm.io/xorm"
)

// MockProductsRepo is a mock of ProductsRepo interface.
type MockProductsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProductsRepoMockRecorder
	isgomock struct{}
}

// MockProductsRepoMockRecorder is the mock recorder for MockProductsRepo.
type MockProductsRepoMockRecorder struct {
	mock *MockProductsRepo
}

// NewMockProductsRepo creates a new mock instance.
func NewMockProductsRepo(ctrl *gomock.Controller) *MockProductsRepo {
	mock := &MockProductsRepo{ctrl: ctrl}
	mock.recorder = &MockProductsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductsRepo) EXPECT() *MockProductsRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProductsRepo) Create(ctx context.Context, product *types.Product, attrs []*types.ProductAttributeValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, product, attrs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProductsRepoMockRecorder) Create(ctx, product, attrs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductsRepo)(nil).Create), ctx, product, attrs)
}

// CreateTx mocks base method.
func (m *MockProductsRepo) CreateTx(ctx context.Context, tx *xorm.Session, product *types.Product, attrs []*types.ProductAttributeValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTx", ctx, tx, product, attrs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTx indicates an expected call of CreateTx.
func (mr *MockProductsRepoMockRecorder) CreateTx(ctx, tx, product, attrs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTx", reflect.TypeOf((*MockProductsRepo)(nil).CreateTx), ctx, tx, product, attrs)
}

// Delete mocks base method.
func (m *MockProductsRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductsRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductsRepo)(nil).Delete), ctx, id)
}

// DeleteTx mocks base method.
func (m *MockProductsRepo) DeleteTx(ctx context.Context, tx *xorm.Session, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTx", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTx indicates an expected call of DeleteTx.
func (mr *MockProductsRepoMockRecorder) DeleteTx(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTx", reflect.TypeOf((*MockProductsRepo)(nil).DeleteTx), ctx, tx, id)
}

// Find mocks base method.
func (m *MockProductsRepo) Find(ctx context.Context, opts *repos.ProductFindOpts) ([]*types.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, opts)
	ret0, _ := ret[0].([]*types.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find indicates an expected call of Find.
func (mr *MockProductsRepoMockRecorder) Find(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockProductsRepo)(nil).Find), ctx, opts)
}

// Get mocks base method.
func (m *MockProductsRepo) Get(ctx context.Context, id int64) (*types.Product, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*types.Product)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockProductsRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProductsRepo)(nil).Get), ctx, id)
}

// Update mocks base method.
func (m *MockProductsRepo) Update(ctx context.Context, product *types.Product, attrs []*types.ProductAttributeValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, product, attrs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProductsRepoMockRecorder) Update(ctx, product, attrs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProductsRepo)(nil).Update), ctx, product, attrs)
}

// UpdateTx mocks base method.
func (m *MockProductsRepo) UpdateTx(ctx context.Context, tx *xorm.Session, product *types.Product, attrs []*types.ProductAttributeValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTx", ctx, tx, product, attrs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTx indicates an expected call of UpdateTx.
func (mr *MockProductsRepoMockRecorder) UpdateTx(ctx, tx, product, attrs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTx", reflect.TypeOf((*MockProductsRepo)(nil).UpdateTx), ctx, tx, product, attrs)
}
