// Code generated by MockGen. DO NOT EDIT.
// Source: ./product_attribute_values.go
//
// Generated by this command:
//
//	mockgen -source=./product_attribute_values.go -destination=./mocks/product_attribute_values.go -package=mock_repos ProductAttributeValuesRepo
//

// Package mock_repos is a generated GoMock package.
package mock_repos

import (
	context "context"
	reflect "reflect"

	repos "github.com/happilymarrieddad/order-management-v3/api/internal/repos"
	types "github.com/happilymarrieddad/order-management-v3/api/types"
	gomock "go.uber.org/mock/gomock"
	xorm "xorm.io/xorm"
)

// MockProductAttributeValuesRepo is a mock of ProductAttributeValuesRepo interface.
type MockProductAttributeValuesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProductAttributeValuesRepoMockRecorder
	isgomock struct{}
}

// MockProductAttributeValuesRepoMockRecorder is the mock recorder for MockProductAttributeValuesRepo.
type MockProductAttributeValuesRepoMockRecorder struct {
	mock *MockProductAttributeValuesRepo
}

// NewMockProductAttributeValuesRepo creates a new mock instance.
func NewMockProductAttributeValuesRepo(ctrl *gomock.Controller) *MockProductAttributeValuesRepo {
	mock := &MockProductAttributeValuesRepo{ctrl: ctrl}
	mock.recorder = &MockProductAttributeValuesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductAttributeValuesRepo) EXPECT() *MockProductAttributeValuesRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProductAttributeValuesRepo) Create(ctx context.Context, attr *types.ProductAttributeValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, attr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProductAttributeValuesRepoMockRecorder) Create(ctx, attr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductAttributeValuesRepo)(nil).Create), ctx, attr)
}

// CreateTx mocks base method.
func (m *MockProductAttributeValuesRepo) CreateTx(ctx context.Context, tx *xorm.Session, attr *types.ProductAttributeValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTx", ctx, tx, attr)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTx indicates an expected call of CreateTx.
func (mr *MockProductAttributeValuesRepoMockRecorder) CreateTx(ctx, tx, attr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTx", reflect.TypeOf((*MockProductAttributeValuesRepo)(nil).CreateTx), ctx, tx, attr)
}

// Delete mocks base method.
func (m *MockProductAttributeValuesRepo) Delete(ctx context.Context, ids ...int64) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductAttributeValuesRepoMockRecorder) Delete(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductAttributeValuesRepo)(nil).Delete), varargs...)
}

// DeleteTx mocks base method.
func (m *MockProductAttributeValuesRepo) DeleteTx(ctx context.Context, tx *xorm.Session, ids ...int64) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteTx", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTx indicates an expected call of DeleteTx.
func (mr *MockProductAttributeValuesRepoMockRecorder) DeleteTx(ctx, tx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTx", reflect.TypeOf((*MockProductAttributeValuesRepo)(nil).DeleteTx), varargs...)
}

// Find mocks base method.
func (m *MockProductAttributeValuesRepo) Find(ctx context.Context, opts *repos.ProductAttributeValueFindOpts) ([]*types.ProductAttributeValue, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, opts)
	ret0, _ := ret[0].([]*types.ProductAttributeValue)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find indicates an expected call of Find.
func (mr *MockProductAttributeValuesRepoMockRecorder) Find(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockProductAttributeValuesRepo)(nil).Find), ctx, opts)
}

// Get mocks base method.
func (m *MockProductAttributeValuesRepo) Get(ctx context.Context, id int64) (*types.ProductAttributeValue, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*types.ProductAttributeValue)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockProductAttributeValuesRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProductAttributeValuesRepo)(nil).Get), ctx, id)
}

// Update mocks base method.
func (m *MockProductAttributeValuesRepo) Update(ctx context.Context, attr *types.ProductAttributeValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, attr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProductAttributeValuesRepoMockRecorder) Update(ctx, attr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProductAttributeValuesRepo)(nil).Update), ctx, attr)
}

// UpdateTx mocks base method.
func (m *MockProductAttributeValuesRepo) UpdateTx(ctx context.Context, tx *xorm.Session, attr *types.ProductAttributeValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTx", ctx, tx, attr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTx indicates an expected call of UpdateTx.
func (mr *MockProductAttributeValuesRepoMockRecorder) UpdateTx(ctx, tx, attr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTx", reflect.TypeOf((*MockProductAttributeValuesRepo)(nil).UpdateTx), ctx, tx, attr)
}
