-- +goose Up
ALTER TABLE companies ADD COLUMN visible BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN visible BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE locations ADD COLUMN visible BOOLEAN NOT NULL DEFAULT TRUE;

-- +goose Down
ALTER TABLE companies DROP COLUMN visible;
ALTER TABLE users DROP COLUMN visible;
ALTER TABLE locations DROP COLUMN visible;