version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: order_mgmt_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test-db:
    image: postgres:15-alpine
    container_name: order_mgmt_test_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres-test
    ports:
      - "5433:5432" # Expose on a different host port to avoid conflicts

volumes:
  postgres_data: